add getApp Details to Passage class
passageidentity/passage-node pull request #32
Opened 2022-05-19 22:56 UTC by himichaelroberts

2022-05-19 23:35 UTC, dylanbrookes requested changes

2022-05-19 23:35 UTC, dylanbrookes commented on src/classes/Passage.ts
> +        }
Is there a reason we're requiring an API key to make this request? The endpoint `https://api.passage.id/v1/apps/{appID}` doesn't require authentication / an authorization header

2022-05-19 23:35 UTC, dylanbrookes commented on src/classes/Passage.ts
> +            })
We likely don't need this authorization header since this is an unauthenticated route

2022-05-19 23:44 UTC, dylanbrookes commented
Looks good - just the one small thing about getting app details without needing the authorization header. Also, thoughts on adding to the readme for the new getApp() method?

2022-05-23 12:58 UTC, calhorn95 commented
@himichaelroberts can you also add documentation for this new function to the README.  Thank you

2022-05-23 16:41 UTC, merged